<?php

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */
function fl_get_meta_box( $meta_boxes ) {
    $prefix_video = 'fl-video';
    $prefix = 'fl-';

    $meta_boxes[] = array(
        'id' => 'home',
        'title' => esc_html__( 'Homepages Content', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // video
            array(
                'id' => $prefix_video . 'content',
                'name' => esc_html__( 'Video', 'metabox-online-generator' ),
                'type' => 'oembed',
            ),
            array(
                'id' => $prefix_video. 'head',
                'type' => 'text',
                'name' => esc_html__( 'Video Head', 'metabox-online-generator' ),
            ),


        ),
    );


    /// Why section
    $meta_boxes[] = array(
        'id' => 'why',
        'title' => esc_html__( 'Why Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // why
            array(
                'id' => $prefix . 'why-head',
                'type' => 'text',
                'name' => esc_html__( 'Why Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'why-subhead',
                'type' => 'text',
                'name' => esc_html__( 'Why Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'why-paragraph',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Why Paragraph', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'why-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Why Image', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'why-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Why Image Button', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'why-url',
                'type' => 'url',
                'name' => esc_html__( 'Why URL Button', 'metabox-online-generator' ),
            ),
        ),
    );

    /// World section
    $meta_boxes[] = array(
        'id' => 'world',
        'title' => esc_html__( 'World Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // world
            array(
                'id' => $prefix . 'world-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'World Background', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'world-head',
                'name' => esc_html__( 'World Head', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'world-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'World Overlay Image', 'metabox-online-generator' ),
            )
        ),
    );

    /// What section
    $meta_boxes[] = array(
        'id' => 'what',
        'title' => esc_html__( 'What Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // what
            array(
                'id' => $prefix . 'what-head',
                'type' => 'text',
                'name' => esc_html__( 'What Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'what-subhead',
                'type' => 'text',
                'name' => esc_html__( 'What Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'what-paragraph',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'What Paragraph', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'what-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'What Image', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'what-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'What Image Overlay', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'what-url',
                'type' => 'url',
                'name' => esc_html__( 'What URL Image', 'metabox-online-generator' ),
            ),
        ),
    );


    /// How it works section
    $meta_boxes[] = array(
        'id' => 'how-it-works',
        'title' => esc_html__( 'How it works Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // how it works
            array(
                'id' => $prefix . 'how-it-works-head',
                'type' => 'text',
                'name' => esc_html__( 'How it works Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-subhead-1',
                'type' => 'text',
                'name' => esc_html__( 'How it works Subhead #1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-paragraph-1',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'How it works Paragraph #1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-subhead-2',
                'type' => 'text',
                'name' => esc_html__( 'How it works Subhead #2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-paragraph-2',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'How it works Paragraph #2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'How it works Image', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'how-it-works-text-image-1',
                'name' => esc_html__( 'How it works Text Image 1', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'how-it-works-text-image-2',
                'name' => esc_html__( 'How it works Text Image 2', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'how-it-works-text-image-3',
                'name' => esc_html__( 'How it works Text Image 3', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'how-it-works-button-text-1',
                'name' => esc_html__( 'How it works Button #1', 'metabox-online-generator' ),
                'desc' => 'button in slide #1',
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'how-it-works-button-text-2',
                'name' => esc_html__( 'How it works Button #2', 'metabox-online-generator' ),
                'desc' => 'button in slide #2',
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'how-it-works-button-link',
                'name' => esc_html__( 'How it works Button Link (not used now)', 'metabox-online-generator' ),
                'type' => 'url',
            ),
        ),
    );

    /// Goal section
    $meta_boxes[] = array(
        'id' => 'giak',
        'title' => esc_html__( 'Goal Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // goal
            array(
                'id' => $prefix . 'goal-head',
                'type' => 'text',
                'name' => esc_html__( 'Goal Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-subhead-1',
                'type' => 'text',
                'name' => esc_html__( 'Goal Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-subhead-2',
                'type' => 'text',
                'name' => esc_html__( 'Goal Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-paragraph-1',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Goal Paragraph 1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-paragraph-2',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Goal Paragraph 2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-button-text-1',
                'type' => 'text',
                'name' => esc_html__( 'Goal Button Text #1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-button-text-2',
                'type' => 'text',
                'name' => esc_html__( 'Goal Button Text #2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-url',
                'type' => 'url',
                'name' => esc_html__( 'Goal URL', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'goal-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Goal Image', 'metabox-online-generator' ),
            ),
        ),
    );

    /// Certificates section
    $meta_boxes[] = array(
        'id' => 'certificates',
        'title' => esc_html__( 'Certificates Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // certificates
            array(
                'id' => $prefix . 'certificates-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Certificates Background', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificates-head',
                'name' => esc_html__( 'Certificates Head', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'certificates-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Certificates Overlay Image', 'metabox-online-generator' ),
                'description' => 'Add the three certificates here',
            ),
        ),
    );

    /// Certificate section
    $meta_boxes[] = array(
        'id' => 'certificate',
        'title' => esc_html__( 'Siegel Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // certificates
            // certificate
            array(
                'id' => $prefix . 'certificate-head',
                'type' => 'text',
                'name' => esc_html__( 'Certificate Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-subhead-1',
                'type' => 'text',
                'name' => esc_html__( 'Certificate Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-paragraph-1',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Certificate Paragraph 1', 'metabox-online-generator' ),
            ),

            array(
                'id' => $prefix . 'certificate-subhead-2',
                'type' => 'text',
                'name' => esc_html__( 'Certificate Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-paragraph-2',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Certificate Paragraph 2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-slider-button-text-1',
                'type' => 'text',
                'name' => esc_html__( 'Slider Button Text #1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-slider-button-text-2',
                'type' => 'text',
                'name' => esc_html__( 'Slider Button Text #2', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Certificate Image', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Certificate Image Button', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-url',
                'type' => 'url',
                'name' => esc_html__( 'Certificate URL Button', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'certificate-button-text',
                'type' => 'text',
                'name' => esc_html__( 'Certificate Text Button', 'metabox-online-generator' ),
            ),
        ),
    );

    /// Numbers section
    $meta_boxes[] = array(
        'id' => 'numbers',
        'title' => esc_html__( 'Numbers Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // numbers
            array(
                'id' => $prefix . 'numbers-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Numbers Background', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'numbers-head',
                'name' => esc_html__( 'Numbers Head ( without decimals )', 'metabox-online-generator' ),
                'type' => 'text',
            ),
            array(
                'id' => $prefix . 'numbers-overlay-text',
                'type' => 'text',
                'name' => esc_html__( 'Numbers Overlay Text', 'metabox-online-generator' ),
            ),
        ),
    );

    /// Standards section
    $meta_boxes[] = array(
        'id' => 'standards',
        'title' => esc_html__( 'Standards Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            // standards
            array(
                'id' => $prefix . 'standards-head',
                'type' => 'text',
                'name' => esc_html__( 'Standards Head', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'standards-subhead-1',
                'type' => 'text',
                'name' => esc_html__( 'Standards Subhead', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'standards-paragraph-1',
                'type' => 'wysiwyg',
                'name' => esc_html__( 'Standards Paragraph 1', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'standards-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Standards Image', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'standards-overlay-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Standards Image Button', 'metabox-online-generator' ),
            ),
            array(
                'id' => $prefix . 'standards-url',
                'type' => 'url',
                'name' => esc_html__( 'Standards URL', 'metabox-online-generator' ),
            ),
        ),
    );

    // array(
//    'id' => $prefix . 'standards-subhead-2',
//                'type' => 'text',
//                'name' => esc_html__( 'Standards Subhead', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-paragraph-2',
//                'type' => 'wysiwyg',
//                'name' => esc_html__( 'Standards Paragraph 2', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-subhead-3',
//                'type' => 'text',
//                'name' => esc_html__( 'Standards Subhead', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-paragraph-3',
//                'type' => 'wysiwyg',
//                'name' => esc_html__( 'Standards Paragraph 3', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-button-text-1',
//                'type' => 'text',
//                'name' => esc_html__( 'Button Text #1', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-button-text-2',
//                'type' => 'text',
//                'name' => esc_html__( 'Button Text #2', 'metabox-online-generator' ),
//            ),
//            array(
//                'id' => $prefix . 'standards-button-text-3',
//                'type' => 'text',
//                'name' => esc_html__( 'Button Text #3', 'metabox-online-generator' ),
//            ),

    /// Standards section
    $meta_boxes[] = array(
        'id' => 'footer',
        'title' => esc_html__( 'Footer Section', 'metabox-online-generator' ),
        'post_types' => array( 'page' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            array(
                'id' => $prefix . 'footer-image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Footer Image', 'metabox-online-generator' ),
            ),

        ),
    );


    return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'fl_get_meta_box' );

function sf_create_metaboxes( $meta_boxes ) {
    $prefix = 'ap-';

    $meta_boxes[] = array(
        'id' => 'project-info',
        'title' => esc_html__( 'Project Info', 'understrap' ),
        'post_types' => array( 'project' ),
        'context' => 'advanced',
        'priority' => 'default',
        'autosave' => false,
        'fields' => array(
            array(
                'id' => $prefix . 'video',
                'type' => 'text',
                'name' => esc_html__( 'Video ID ', 'understrap' ),
                'description' => 'This is the unique id of the video usually in like this228414948. Only VIMEO supported',
                'std' => '229545027',
            ),
            array(
                'id' => $prefix . 'client',
                'type' => 'text',
                'name' => esc_html__( 'Client Name', 'understrap' ),
                'std' => 'Test Company GmbH',
            ),
            array(
                'id' => $prefix . 'area',
                'type' => 'text',
                'name' => esc_html__( 'Short Description', 'understrap' ),
                'std' => 'This is a short description for this movie',
            ),
            array(
                'id' => $prefix . 'additional image',
                'type' => 'image_advanced',
                'name' => esc_html__( 'Extra Image', 'understrap' ),
            ),
        ),
    );

    return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'sf_create_metaboxes' );

